In [1]:
import pandas as pd
import numpy as np

In [3]:
consumer = pd.read_excel(r"C:\Users\amanb\Downloads\Customer_Complaints\Consumer_Complaints.xlsx")

In [4]:
consumer

,Complaint ID,Submitted via,Date submitted,Date received,State,Product,Sub-product,Issue,Sub-issue,Company public response,Company response to consumer,Timely response?
0,4848023,Referral,2021-10-24,2021-10-27,NY,Mortgage,Conventional home mortgage,Applying for a mortgage or refinancing an exis...,NaN,Company has responded to the consumer and the ...,Closed with explanation,Yes
1,3621464,Web,2020-04-24,2020-04-24,FL,"Money transfer, virtual currency, or money ser...",Refund anticipation check,Lost or stolen check,NaN,Company has responded to the consumer and the ...,Closed with monetary relief,Yes
2,5818349,Web,2022-07-27,2022-07-27,CA,"Credit reporting, credit repair services, or o...",Credit reporting,Incorrect information on your report,Account information incorrect,Company has responded to the consumer and the ...,Closed with explanation,Yes
3,7233015,Referral,2023-07-10,2023-07-11,CA,Credit card or prepaid card,General-purpose prepaid card,Problem getting a card or closing an account,"Trouble getting, activating, or registering a ...",NaN,In progress,NaN
4,5820224,Referral,2022-07-27,2022-07-28,VA,Credit card or prepaid card,General-purpose credit card or charge card,Closing your account,Company closed your account,Company has responded to the consumer and the ...,Closed with explanation,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...
62511,2501211,Web,2017-06-04,2017-06-04,TX,Checking or savings account,Checking account,Managing an account,Problem using a debit or ATM card,Company has responded to the consumer and the ...,Closed with explanation,Yes
62512,2472406,Referral,2017-05-01,2017-05-05,VA,Checking or savings account,Other banking product or service,Problem caused by your funds being low,Non-sufficient funds and associated fees,Company has responded to the consumer and the ...,Closed with explanation,Yes
62513,3704015,Web,2020-06-17,2020-06-17,TN,"Credit reporting, credit repair services, or o...",Credit repair services,Confusing or missing disclosures,NaN,Company has responded to the consumer and the ...,Closed with explanation,Yes
62514,2488973,Referral,2017-05-19,2017-05-19,GA,Mortgage,Other type of mortgage,Trouble during payment process,NaN,Company has responded to the consumer and the ...,Closed with explanation,Yes
62515,6234542,Web,2022-11-22,2022-11-22,CA,"Money transfer, virtual currency, or money ser...",International money transfer,Fraud or scam,NaN,Company has responded to the consumer and the ...,Closed with explanation,Yes

In [24]:
consumer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62516 entries, 0 to 62515
Data columns (total 12 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   complaint id                  62516 non-null  int64
 1   submitted via                 62516 non-null  object
 2   date submitted                62516 non-null  datetime64[ns]
 3   date received                 62516 non-null  datetime64[ns]
 4   state                         62516 non-null  object
 5   product                       62516 non-null  object
 6   sub_product                   62516 non-null  object
 7   issue                         62516 non-null  object
 8   sub_issue                     62516 non-null  object
 9   company public response       62516 non-null  object
 10  company response to consumer  62516 non-null  object
 11  timely response?              62516 non-null  object
dtypes: datetime64[ns](2), int64(1), object(9)
memory usage: 5.7+ MB

In [5]:
consumer.describe()

,Complaint ID,Date submitted,Date received
count,6.251600e+04,62516,62516
mean,4.512642e+06,2020-11-24 16:07:14.883869696,2020-11-25 21:31:05.071341568
min,2.471340e+06,2017-05-01 00:00:00,2017-05-01 00:00:00
25%,3.254020e+06,2019-05-22 00:00:00,2019-05-28 00:00:00
50%,4.178582e+06,2021-03-02 00:00:00,2021-03-03 00:00:00
75%,5.771284e+06,2022-07-14 00:00:00,2022-07-15 00:00:00
max,7.458912e+06,2023-08-28 00:00:00,2023-08-28 00:00:00
std,1.442917e+06,NaN,NaN

In [6]:
consumer.isnull().sum()

Complaint ID                        0
Submitted via                       0
Date submitted                      0
Date received                       0
State                               0
Product                             0
Sub-product                         7
Issue                               0
Sub-issue                       10858
Company public response          2175
Company response to consumer        0
Timely response?                 1494
dtype: int64

In [7]:
consumer.shape

(62516, 12)

In [8]:
consumer["Sub-issue"] = consumer["Sub-issue"].fillna("Not defined")

In [9]:
consumer.isnull().sum()

Complaint ID                       0
Submitted via                      0
Date submitted                     0
Date received                      0
State                              0
Product                            0
Sub-product                        7
Issue                              0
Sub-issue                          0
Company public response         2175
Company response to consumer       0
Timely response?                1494
dtype: int64

In [10]:
consumer["Company public response"] = consumer["Company public response"].fillna("Not provided")

In [11]:
consumer["Timely response?"] = consumer["Timely response?"].fillna("N.A")

In [12]:
consumer.isnull().sum()

Complaint ID                    0
Submitted via                   0
Date submitted                  0
Date received                   0
State                           0
Product                         0
Sub-product                     7
Issue                           0
Sub-issue                       0
Company public response         0
Company response to consumer    0
Timely response?                0
dtype: int64

In [13]:
consumer["Sub-product"] = consumer["Sub-product"].fillna("N.A")

In [14]:
consumer.duplicated().sum()

np.int64(0)

In [15]:
consumer.columns

Index(['Complaint ID', 'Submitted via', 'Date submitted', 'Date received',
       'State', 'Product', 'Sub-product', 'Issue', 'Sub-issue',
       'Company public response', 'Company response to consumer',
       'Timely response?'],
      dtype='object')

In [16]:
consumer.columns = consumer.columns.str.replace("-","_")
consumer.columns = consumer.columns.str.lower()

In [17]:
consumer.columns

Index(['complaint id', 'submitted via', 'date submitted', 'date received',
       'state', 'product', 'sub_product', 'issue', 'sub_issue',
       'company public response', 'company response to consumer',
       'timely response?'],
      dtype='object')

In [18]:
consumer = consumer.rename(columns = {"timely_response?" : "timely_response"})

In [19]:
consumer.columns

Index(['complaint id', 'submitted via', 'date submitted', 'date received',
       'state', 'product', 'sub_product', 'issue', 'sub_issue',
       'company public response', 'company response to consumer',
       'timely response?'],
      dtype='object')

In [20]:
consumer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62516 entries, 0 to 62515
Data columns (total 12 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   complaint id                  62516 non-null  int64
 1   submitted via                 62516 non-null  object
 2   date submitted                62516 non-null  datetime64[ns]
 3   date received                 62516 non-null  datetime64[ns]
 4   state                         62516 non-null  object
 5   product                       62516 non-null  object
 6   sub_product                   62516 non-null  object
 7   issue                         62516 non-null  object
 8   sub_issue                     62516 non-null  object
 9   company public response       62516 non-null  object
 10  company response to consumer  62516 non-null  object
 11  timely response?              62516 non-null  object
dtypes: datetime64[ns](2), int64(1), object(9)
memory usage: 5.7+ MB

In [21]:
consumer.count()

complaint id                    62516
submitted via                   62516
date submitted                  62516
date received                   62516
state                           62516
product                         62516
sub_product                     62516
issue                           62516
sub_issue                       62516
company public response         62516
company response to consumer    62516
timely response?                62516
dtype: int64

In [27]:
consumer.columns = consumer.columns.str.replace(" ","_")

In [30]:
consumer = consumer.rename(columns = {"timely_response?" : "timely_response"})

In [31]:
consumer.columns

Index(['complaint_id', 'submitted_via', 'date_submitted', 'date_received',
       'state', 'product', 'sub_product', 'issue', 'sub_issue',
       'company_public_response', 'company_response_to_consumer',
       'timely_response'],
      dtype='object')

In [32]:
from sqlalchemy import create_engine

engine = create_engine("mysql+pymysql://root:aman123@localhost:3306/Financial_complaints")

consumer.to_sql(
    name="complaints_analysis",
    con=engine,
    if_exists="replace",   
    index=False
)

62516

In [33]:
consumer.to_csv("complaints_analysis.csv",
index = False, encoding = "utf-8-sig")